### ISSUE TITLE
Investment Flow

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1212]
Ticket onboarding:

https://projects.invisionapp.com/d/main#/projects/prototypes/14205800

**Comment by rudolfix** [comment]
First step IMO should be the calculator (of token and neu) and it is also the easiest. When you are in context of eto data (public profile), this eto data is loaded by id. this id is an address of smart contract (only if eto.state is "on_chain", in other states investment is impossible because contracts are not deployed - see https://github.com/Neufund/platform-backend/wiki/5.7.-Use-Case-ETO-Listing).
Now when we are on_chain we can load smart contract. artifact name is "ETOCommitment", see ContractService to see how to get contract instance by address and artifact name.
Now smart contract has its own set of states (https://github.com/Neufund/platform-backend/wiki/5.6.-Use-Case-Investment)

Investment is possible in two states (call ETOCommitment.state()) to get the state: 1 - Whitelist and 2 - Public. For both of those states the only thing to do to implement calculator is to call `calculateContribution`: https://github.com/Neufund/platform-contracts/blob/master/contracts/ETO/ETOCommitment.sol#L479

you need provide: investor address, flag if investment happens via ICBM wallet and the amount invested (by default we invest minimum ticket that you can get from eto data).

returned are
- is user allowed to invest in whitelist
- minimum ticket (error is user typed less money)
- maximum ticket
- how many equity tokens user gets
- how many neu user gets
- is maximum cap of whitelist or public was exceeded (if so user needs to lower the amount)

that should be enough for a start. if you need to convert eur to eth use data from token price oracle that I added in last PR

**Comment by trival** [comment]
so far investments with the ether token wallet are possible. Many little fine tunings are still missing, as well as the investments with other wallets. 

Missing Details: Translations, Layout improvements, Invest whole wallet amount button

**Comment by glupiawymowka** [comment]
[dev environment tested] not deployed to stage yet

1. min. and max investment value error labels need new wording
![image](https://user-images.githubusercontent.com/18315589/45487963-2dec3b80-b760-11e8-8c40-735d558004d8.png)

2. "Invest Entire Wallet Balance" is not a working button yet

3. NEU reward calculator not working at all
![image](https://user-images.githubusercontent.com/18315589/45488114-9d622b00-b760-11e8-9f71-f378580e8788.png)

4. ModalComponentBody-module_body : "signer" sounds really strange. Maybe we should adopt the message from the similar cases? 
Also the styling should be the same (centered text)
![image](https://user-images.githubusercontent.com/18315589/45488146-b23ebe80-b760-11e8-877f-69320db1d4de.png)
