### ISSUE TITLE
ETO Dashboard. Fixes

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1335]
<img width="654" alt="screen shot 2018-09-12 at 12 43 06" src="https://user-images.githubusercontent.com/2290474/45420069-708f1480-b689-11e8-8534-926423e971c8.png">

- [ ] Pls. make thumbnail visible. To test on Staging tomorrow

- [x] Company URL: pls. show only neufund.org (So in the format https://xxxx.com we wanna show only xxxx.com as a link.

- [x] PitchDesh in the iFrame will not work. Pls. drop it and simply redirect to link on the separeate website.  To test on stagign tomorrrow.

**Comment by lizonp** [comment]
@SergejSoft  I suppose that thumbnail doesn't show because of security reasons. Slideshare works quite well, but you need to remember to share iframe's url.
<img width="742" alt="screen shot 2018-09-12 at 16 34 09" src="https://user-images.githubusercontent.com/12571855/45432318-dee3cf00-b6a9-11e8-9d4b-c0f00efe0edf.png">
<img width="845" alt="screen shot 2018-09-12 at 16 31 26" src="https://user-images.githubusercontent.com/12571855/45432319-dee3cf00-b6a9-11e8-9f12-6ac73fd30a69.png">
