### ISSUE TITLE
Issuer Dashboard: Token Holder Rights/Voting form: problem with default null value on save form

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1464]
liquidation_preference_multiplier - select box.

if selection is never happens, null is inserted and backend fails.
steps: go there with new account. set voting rights to "no". save. you have 400 bad request

**Comment by AlexeyTuboltsev** [comment]
We must discuss it with Marcin and Dave. 
The real issue here is that we have optional values in our model, but no way to express that the value is not set, apart from omitting the field. We end up with sending around incomplete structures. This creates a whole bunch of problems if trying to unset an already set field or trying to express explicitly, that the user didn't wish to set a field (because it was optional!). 
We need to convert all our optional fields to type null|<possible values>, because it's the only way to send an unset val over the wire (?)

**Comment by rudolfix** [comment]
I agree with this. please see #1548 
instead of setting those fields undefined we may set them to null (for all optional fields that are undefined or set to empty values - see bug in formik described there). there is enough metadata in yup schema to do it.

**Comment by rudolfix** [comment]
please make PR from https://github.com/Neufund/platform-frontend/compare/at/%231464-issuer-dashboard-default-null-values so we can review it! IMO it goes in good direction I'd like to leave some comments
