### ISSUE TITLE
cannot invest minimum ticket from Ether wallet - are we losing precision?

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1514]
steps to reproduce
1. Select ETH Investment wallet
2. Type 100 EUR (which is minimum ticket) in Euro Amount
3. Confirm and sign transaction
4. Transaction will revert

IMO transaction reverts because what happens is that 100 EUR is converted into ETH via price oracle and this amount is sent to smart contract which calculates it back to euro. I suppose when you do your calculation you round value somehow or you round it differently than smart contract. Please check the following
1. we have price from price oracle in full precision (up until wei) in state. it's not rounded at any point
2. you do all conversions on BigNumbers. js numbers are never used
3. you do not round to 4 decimal places etc. you always use wei precision and round only to display
4. when converting EUR to ETH you probably use inverse price somewhere. correct? do not calculate inverse yourself, take it from smart contract (at the same time we take other rates - you can ask for multiple rates in the same call what I hope we do). just ask EUR to ETH price (we already ask ETH to EUR)
5. in all price conversions we'll use div() please round results of div as follow number.div(number).round(0, 4) so you round as smart contract rounds

**Comment by trival** [comment]
@rudolfix I have implemented all your suggestions. Still the problem is not with rounding.
In Ether investment, the fixed value is always the ether value, and Euro is always only estimation, calculated from ether price. When token price oracle changes, the eth value stays fixed, the euro value is recalculated. This is because it is Ether investment! But of course, if price goes up, the euro goes below the minimum automatically. 

The problem is, I have to keep one value that is the source of truth, and one that is calculated. Which one should I choose?? Eur or Eth? The same problem is with the invest full Wallet edge case. I think we cannot handle these border conditions 100% correctly with all these conversions going on...

**Comment by glupiawymowka** [comment]
min ticket is working now
