### ISSUE TITLE
[EMAIL VERIFICATION] - strange feature behaviours - IMPORTANT

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1571]
1. ledger is locked, new email added. **The message should say to unlock the ledger and confirm email**, this is what happens instead:
gif https://drive.google.com/open?id=1c7UClNYPQd--ABXB3wvTqt56oJmQWEpP
it's too fast to even read what happens, but this is the message that appears: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/1d833d20-7981-4a68-bf75-334553a8f947)
the instruction is to CONFIRM,  there shouldn't be CANCEL button
**Verification email should not be sent when nothing was confirmed**
An information that the ledger needs to be unlocked should appear first if it's locked 

2. Same for "Resend link" option - ledger is locked, nothing was confirmed, the screen appears for less than a second WITH the information that ledger is locked, then link is resent anyways
gif: https://drive.google.com/open?id=10PJQgfeqrpN_1g2DKsg2K4grTnlA9_LE

3. Ledger connected. I should confirm the transaction on it. This is the screen I get : 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f1685bc8-f864-4d96-8247-500fe5a21a09)

It's confusing, again, why the instruction says "confirm" and the only option to choose is "cancel".

**Comment by rudolfix** [comment]
It was always like that:
1. Text says: confirm on your ledger. But this is apparently not enough. We should add some ledger icon so people see where they need to press (like we have in starting tutorial) @falinebambi?
2. It disappears because we already have permission to change/set e-mail from previous clikcs. I just checked - first time it waits next time not. but here it's so fast that I cannot even see the dialog. 
My take is that the check if we have permission is done after component is displayed, @Moejoe90 correct?

**Comment by AlexeyTuboltsev** [comment]
Neither me nor @glupiawymowka could reproduce this. Let's close for now
