### ISSUE TITLE
Limiting investment if KYC is not completed 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#1612]
Limiting users to not be able to invest unless KYC has been completed 

For example Marcin did not started KYC process and was able to invest

**Comment by rudolfix** [comment]
hey @shanile it was something else that happend with my account. I can explain that later. KYC situation is prevented by smart contract. It will not happen. Regarding frontend indeed investment button is visible not not verified users. this will be fixed by this ticket
https://github.com/Neufund/platform-frontend/issues/1459
