### ISSUE TITLE
Show pdf documents in second tab, not download

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2019]
Can we open all links to pdf documents in a **separate tab** instead of immediate download? 
This logic could be applied for different documents in the platform.
The user is not prepared to immediately download when clicking on links.

This considers:
Terms and Condition.

TAGS in widget:
- Term sheet, 
- investment memorandum, 
- prospectus approved

All legal agreements in popups and portfolio

Unfortunately I cannot manipulate it with wording since the TAGs would break then:
![image](https://user-images.githubusercontent.com/26923972/48935043-867d4900-ef06-11e8-8564-984012da38d6.png)

**Comment by Moejoe90** [comment]
@SergejSoft 
This proved to be a bit more complicated as chrome blocks links coming from the frontend. 
It would be easier if we have a direct link to the document but because its coming from the backend as a BLOB chrome is blocking it. 

The best way to solve this problem is to maybe view this PDF online, but mind you this will make the whole application bigger

**Comment by pstroinski** [comment]
@Vanilizer how important is it?
