### ISSUE TITLE
Font change in Dashboard

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2181]
Please change font on dashboard for the text below "Investment Opportunities"
![image](https://user-images.githubusercontent.com/26923972/49571890-c39bff00-f93a-11e8-9111-677e1d29c7d6.png)

**Comment by Louisswryan** [comment]
Zep link:   https://zpl.io/2G9MdLd

(Change text under "INVESTMENT OPPORTUNITIES" to LATO LIGHT)

**Comment by Louisswryan** [comment]
Apologies,

I made this change in my first week and neglected to send through to the dev column.

I have updated the design to suit the current style. 

Do not implement the font size changes. We are gradually doing this in design so that we can make the change all at once on the front end.

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c7fb2bf981c3b6256f9eed8

**Comment by AlexeyTuboltsev** [comment]
according to @Louisswryan nothing to do here
