### ISSUE TITLE
Migration tool - improving text 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#2479]
Hi,

I would like to improve the migration tool flow in order to be clear with the purpose of it.

I went through the process with Nikola and technically the process is clear however wording wise we can improve the message to make it more clear.

Today the users believe that they are transferring their NEU using the smart contact address we want to avoid it the purpose of migration tool is to transfer their ETH commitment from unsupported wallet to the wallet on the platform. 

**Suggestion:** 

1. To change the tooltip message on the migration widget and explain that here the user will be able to transfer his ETH commitment from his ICBM wallet to this wallet ( the one he has on our platform). See current content:

![image](https://user-images.githubusercontent.com/36156487/53012621-c9868400-3443-11e9-90b1-32a9fe300503.png)

suggested content: The Migration Tool is specifically intended for Neufund investors who participated in the ICBM in December 2017 and would like to transfer their locked ETH commitment to the wallet associated with their Neufund account.

2. Instead of showing the ICBM wallet balance to show the ETH commitment / locked funds which will be transferred using this tool.

![image](https://user-images.githubusercontent.com/36156487/53012686-02265d80-3444-11e9-9fd3-090469b40477.png)

_*** We can add 1 sentence saying in order to transfer your NEU please read this and add this link https://support.neufund.org/support/solutions/articles/36000120697-i-bought-neu-on-an-exchange-how-do-i-transfer-it-to-my-neufund-account-_

**Comment by Louisswryan** [comment]
Hello,

We are rewording our Migration Tool card and restructuring the module.

As well as this, we are implementing a new solution for tool tips. Rather than justifying the need for a bit of functionality with standard tool tip modal, we will start to use tool tips to define technical language, which is often the main point of confusion.

these language tips will be identified by the word in question being one level of boldness above the surrounding text and will be in the #BASE blue (#394651) as identified on Zeplin.

For the tip box, let's make it exactly the same style that we have used up until this point for the sake of consistency with existing tool tips.

Below are the changes to be made to the Migration Tool and the first implementation of this new tip function.

Thanks!

ICBM_MIGRATION_1
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c7e6a6d86d8b8629231fd38

ICBM_MIGRATION_1 (with language tip)
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c7e6a6e981c3b6256e9dc02

ICBM_MIGRATION_2
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c7e6a6fa481f9bcdf7a8dde

**Comment by falinebambi** [comment]
![Screenshot 2019-03-11 at 15 25 17](https://user-images.githubusercontent.com/17235402/54131076-e6deba80-4411-11e9-91e3-08ae302167f0.png)

This is also a universal styling change to Tooltips which will now be signified by a dotted underline. 

Font size: 12px
Line height: 16px  
Font weight: 400

We will follow Material Design logic for the behaviour or tooltips.  
https://material.io/design/components/tooltips.html#behavior
![Screenshot 2019-03-11 at 14 29 17](https://user-images.githubusercontent.com/17235402/54127502-34efc000-440a-11e9-9870-b21e9cfb99df.png)
