### ISSUE TITLE
Download NEU token agreement 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#2707]
I wanted to accept my NEU payout -- I clicked accept thanI wanted to download the NEU token agreement and I was directed to ICBM commitment page https://commit.neufund.org/commit/status?address=0x32E6a41D091bb5214A9419CC07a5B5EAe87a5152 

I am not an ICBM investor therefore I cannot get the agreement 
![image.png](https://images.zenhubusercontent.com/5ad7083e4b5806bc2bcf94d2/88e9b1d2-e7a4-4897-b752-baa224c5c8ae)

The question is if this behavior is correct, in the next ETO, not all the investors will be an ICBM shouldn't we change the fllow

**Comment by banciur** [comment]
@glupiawymowka Bug is caused by fact that on commit we are using `ipfs.org` and it was behaving hectic and some request weren't finishing. If you could see them pending then app wouldn't have all required data to generate agreements

![image](https://user-images.githubusercontent.com/5120930/56286039-f93acb00-6118-11e9-91a9-e70b3f75e6a0.png)

**Comment by glupiawymowka** [comment]
working fine now
