### ISSUE TITLE
Issuer "Whitelist enabled" component layout issues

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2856]
When an ETO is in whitelist, an Issuer can login to the Dashboard and see the Total amount committed and the number of whitelisted investors.

This component has some layout and design issues and it does not show the commitment amount when the amount is 0.  It should show 0 EUR if no commitments currently exist.

The task is to improve the layout and design of this component and recommend improvements we can make.

<img width="1004" alt="issuer-design-changes-001" src="https://user-images.githubusercontent.com/609657/57199970-aae55300-6f85-11e9-8581-48f0b6b508da.png">

**Comment by Louisswryan** [comment]
Hello,

The whitelisting phase of the issuer flow had a couple of problems which have been reviewed in the following designs.

We should have each of these states to properly reflect the whitelist status.

DISABLED WHITELIST
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e9eb1f2f1e220e0bf6

ENABLED WHITELIST
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e96a41202aace9ccef

FULL WHITELIST
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e9a2d3301e402f9bd9

OUT OF TIME WHITELIST
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e990276b2a9a7f23ad


Also, the presale card needs to be updated. It is unclear what is being communicated in the countdown. It is actually how long the issuer has left to change the presale date. This needs to change to the actual date of presale as shown in the designs above.

Should the issuer wish to change their date of presale, we have an updated flow for this as well.

DATE CHANGE 1
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e9ff497d1e2592061e

DATE CHANGE 2
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e96c73511dec3126d4

DATE CHANGE 3
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ce3c1e93355f82ab28d3a3a

Please ask if you need clarification.

Thanks!

**Comment by glupiawymowka** [comment]
@Louisswryan before this is done, I have some questions regarding consistency in all the modals. 
1. I see that the content is centered in the modals. Is it our new approach that needs to be changed globally? *This green "|" looks a bit strange when almost in the middle of the modal, but this is just an opinion here :D*
2. Do we plan to change globally change the buttons in modals, too? Currently they don't have the borders 
3. "Confirm your documents" section. 
Now we have this: 
![image](https://user-images.githubusercontent.com/18315589/58428598-507e7480-80a3-11e9-94af-d0586c6c40ed.png)
now @andywalton 
We aim to this, which is good but I worry that the given copy is not informative enough (see the previous one). Maybe it would be good to have something in between? 
![image](https://user-images.githubusercontent.com/18315589/58428703-a0f5d200-80a3-11e9-9e68-e356408d69d0.png)

**Comment by Louisswryan** [comment]
I have reviewed this ticket and will approach it a bit differently.

The below design addresses the whitelisting presentation and leaves the presale card more or less the same:
https://zpl.io/29w6YNz

Can we please include all of the whitelisting states as specified previously.

The other important change is that the presale countdown now counts down to the actual date of presale rather than the date when a date change is no longer possible.

Below is the Presale card with dropdown date change feature activated:
https://zpl.io/VDArpGv

Lastly, the modal:
https://zpl.io/2yqQ119

We are keeping to the one modal rather than the flow but the content is laid out differently.

Please note that we now include the option to copy addresses and the two documents have a direct pdf download option. In this way, clicking on the document title directly takes the user to the new tab where the document is viewable.

I put way too many new features into the first round of this ticket so apologies for that! From now, I will make designs closer to the platform and changes to features (which are still coming) will be outlined as separate tickets.

@glupiawymowka is included in this ticket and will be assigned to all future tickets I write so that we are all on top of what is planned for design before it gets to dev (and any time is potentially lost).

Any questions about the plan above please let me know.

Much appreciated!

**Comment by pstroinski** [comment]
To be moved to asana and then please create specific tickets @andywalton
