### ISSUE TITLE
Trans-History #4. Modal Content

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2890]
Hello @desfero ,

This part is probably the trickiest so maybe we can conference about it via Slack.

It is only tricky because of the number of states and potential layouts. For now, let's apply the google doc pretty much as it is laid out.

https://docs.google.com/document/d/1ileQzHNis9RBHmZc6bHE2cF9kj7PCyUXAZEFYXSQpnY/edit

Trevor suggested that for now, the simplest way to order information from the API is alphabetically so let's do that first and we can develop an information hierarchy later.

Below is a guide for how the content should fit within the modal

Modal Content guide:
https://zpl.io/2Egn4ll

This design leaves us with space for 7 fields within the modal.

You will notice that investment in the Google doc has 8 fields. The "is ETH or nEUR Investment" does not apply as we should put the currency of the investment always in the event title. So "Eth Investment" is the title. 

Furthermore "in" transactions are represented with a 'success green' in bold amount value to show that funds came onto the investors' platform. This green value also applies to NEU rewards and token claims as they are also funds coming onto the platform. Conversely, funds leaving the platform are represented in regular black font.

There are quite a few states so let's talk more about it if you want anything cleared up.

Cheers!

**Comment by Louisswryan** [comment]
Hello @desfero ,

This part is probably the trickiest so maybe we can conference about it via Slack.

It is only tricky because of the number of states and potential layouts. A solution that I discussed with Trevor, is to use 

Modal Content guide:
https://zpl.io/2Egn4ll

**Comment by rudolfix** [comment]
Green vs. Black

all transactions which have amount and have direction `in` should be green. for `out` black.

**important elements transaction types**
as we do not have designs for transaction types, let's start with following
- for all transactions we show timestamp and link to etherscan
- transactions status is always Complete, but you can repurpose it for transactions that have updates (see below)
- from and to addresses sometimes have known interfaces. if we know interface we should show it's name instead (I will help you with translations)


**eto investment**
- investent basics: in company name, you can link to their profile, asset token amount and symbol and ICON OF THE TOKEN (ask Louis where to put it)
- investment currency and amount (always show euro equivalent)
- NEU reward
- flag if icbm funds were used (see below)
- a clear indication if tokens were claimed or refunded, if not we should show clearly that this is still pending (it may make sense to show eto_status here and some call to action if user can do it but didn't do it yet)
- if claimed/refunded we can show exact date if this happen
- we do not have any info on tx fees, you could pull it from chain directly via hash (but I do not see any benefit for the user)


**transfer**
- amount
- from/to (if we have any metadata use it, if you have interface name, translate it to string), I will help you with translations
- for all tokens use SYMBOL and ICON (you have one in equity tokens in metadata, you know those for NEU, you have icons for ETH and EUR as well)
- for all tokens mind DECIMAL value, you have it in metadata. do not blindly convert with 18wei. equity has 0 precision
- for equity tokens you can show company name, link to profile

**neur purchase**
- amount
- do not show reference, it's meaningless ;/
- say clearly who is setting transactions like
"Purchase handled by: Quintessence UG"

**neu redeem**
- amount
- "Bank Reference: `: `reference`
- `Redeemed by: Quintessence"
- a very clear indication if bank transfer was sent - see info on updates below
- settled amount, bank fee, when bank transfer was sent

**neur_destroy**
Please name transaction itself `Liquidated nEUR`
- amount
- `Liquidated By` : `Fifth Force Lichtenstein"

**payout** and **redistribute_payout**
- name amount "Amount Paid" or "Amount Redistributed"
- amount, currency, euro equivalent
- paying token: always NEU

**eto refund**
- investent basics: in company name, you can link to their profile, asset token amount and symbol and ICON OF THE TOKEN (ask Louis where to put it)
- amount refunded, currency, eur equivalent
- info "Assets returned due to refund": "NEU" + EQUITY TOKEN NAME

**eto_tokens_claim**
- investent basics: in company name, you can link to their profile, asset token amount and symbol and ICON OF THE TOKEN (ask Louis where to put it)
- amount of equity token claimed
- amount of NEU grant claimed (if > 0)

btw. there's no `deposit` transaction type contrary to swagger, will be removed now


transaction_details that can be updated when requesting new transactions.

**neur_redeem**
before update
`amount` - amount withdrawn by the user
`reference` - reference in bank transfer
`by_address` - you can always put following info `Redeemed by: Quintessence"

after update
before +
`settled_amount` - amount sent in bank transfer (-fee)
`settled_at` - to show date when bank transfer was sent out
also some icon saying that transfer was sent out would be nice

**eto_investment**
before_update
- show all the usual staff as per design
- if funds from ICBM were used then `wallet_address` != investor address, also NEU will be 0

after_update:
`is_claimed` or `is_refunded` will be set to true
`settled_at` - when this action happened
`settled_tx_hash` - if you want to do second link to etherscan with claim/refund transaction

**Comment by Louisswryan** [comment]
Hey @desfero below are the updated designs for modal content

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5d2c426c3e2b55639c6d2ca5

Investment

Pending - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c93bf98a8034c2219a69c

In Campaigning - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c93bfa898614c580afd10

nEUR Investment - 
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425a45a0615ce8133bf3

ICBM Investment - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b16a95f4c64e0e97f

Transfer 

NEU - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425bb86fcc4c403414ff

Token - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b7ff0064cb938ce9d

Purchase

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b166b0c63de4be845

Redeem

NEU - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b1787026b58f95a53

nEUR - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c93bfdfb0f326b1cb2c6d

Destroy

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b5b67f14c5e0ebe39

Payout

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c425b617e0f63d8dca1c1

Redistribute

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c93bea1f25163f007e2a5

Refund

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5d2c93bf7e42384cb3b6e7cd

You will notice we have also done away with the use of green in the modals. In the transaction history, this in/out indicator is perfect but within the modal, it adds complication.

I will now work on a universal modal to bring this into our new styleguide. Also I will update our token icons. There will be a number of different issuer token icons but ours (nEUR, NEU, ETH) will belong to the same family.

Please ask if you have questions. Thanks!

**Comment by glupiawymowka** [comment]
it is ok on stage, just the timestamp shows "In X hours", backend problem being solved in another ticket
