### ISSUE TITLE
ETH Withdrawal UI Review

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3126]
Project Link - https://zpl.io/2GAJWer

Hello,

Designs are ready for the ETH Withdraw feature.

Basic transfer editor

NEW TRANSFER
- https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d1240cca41ede711b2f2877

Error states that appear if entered information is problematic

ERROR STATES
- https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d1240dddb07c27116939c93

Checked box state for certain errors which activates CTA

BOX CHECKED
- https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d1b3dba48d5685ac008a658

Summary page with status updates for Pending and Completion

SUMMARY
- https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d124126281c595a1ed71e27

Please let me know if there are any issues.

Thanks!

**Comment by Moejoe90** [comment]
@Louisswryan 
As discussed there are a couple of things we will need to change and for design to figure out 

1 - Having the `Transfer all` as a feature or check box once activated the user shouldn't be able to enter any amount 

2 - Due the big variation in gas limit depending on the given address we need to disable the amount or somehow force the user to enter the address first why 

without that we can't know if the user has enough money etc

**Comment by Moejoe90** [comment]
After discussion and review we have reached a couple of working actions points: 

1 - Gas Price will have the value of < 0.0001 instead of 0.0000 which doesn't make sense
2 - We will read the intent of the user as in if the value entered manually equals the highest rounded amount we will assume that the user wants to activate the full amount transfer 
3 - Once the user clicks transfer all button the highest rounded amount will be entered into the value field

4 - As long as no valid address was entered the user can still enter a value to transfer and also conduct a transfer all operation with the use of a random address as input. The transaction should never follow through until a valid address is entered but never the less. It is agreed that the cases where bad UX will show is very minimal till the point where we can discard. 

5 - Transfer all will have a separate flow. The flow will be activated once the intent to transfer the full amount is found 

6 - Tests that check entered values with the Real node will be written as a blue print for all important transactions. As its important to assert if the transactions generated by UX translate into correct transactions to the node

**Comment by Louisswryan** [comment]
Hello

**Comment by Louisswryan** [comment]
We have new wording for the mined and unmined cancellation messages that appear in the tx summaries @moejoe90,

If tx mined:
- Your transaction was cancelled. All funds have been returned but a small transaction fee has been paid. For more information, please contact our Customer Care here.

If tx unmined:
- Your transaction was cancelled. All funds have been returned and no transaction fee has been paid. For more information, please contact our Customer Care here.

The reason for this is, 'customer support' is out of line with current language guidelines. Also the current wording makes contacting Neufund seem more necessary than it is.

Thanks!
