### ISSUE TITLE
Registering denied when re-logging

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3214]
**Description**
When I log with nano ledger, then log out and switch to metamask, backend responds with 403 on `create` attempt. Metamask signer is launched correctly but nano ledger UI is visible

![image](https://user-images.githubusercontent.com/17202864/61532971-cb249a00-aa2b-11e9-8341-7ead55acf99a.png)

**Environment**
Found on stage, logging with nano ledger then switching to metamask with `0xE6Ad2CdBA2FB15504232eBFa82f64c06c87F9326` fixture (which also exists on stage)

**Steps To Reproduce**
1. login with ledger then try to use eth withdraw
2. go to login and choose metamask (or in fact any other address on ledger)
3. ledger UI appears but you see correct Metamask signer
4. Sign
5. Be denied access

**Actual behaviour**
User cannot log in when wallet type is switched

**Expected behavior**
User should be able to log in and correct UI should be desplayed

**Comments, context, logs**
What happens under the hood is that
1. backend gets a challenge formatted for Metamask but for address of the logged out nano ledger `"0x64Be85331949105Eb0459B936abF474710B4601b"`
2. signature is taken from Metamask
3. backend returns 403 on create as of course address does not match

**I cleared local storage, didn't help!**

**Screenshots**

**Comment by drakkein** [comment]
I'm unable to reproduce. It seems that it might be connected to previous broken Withdraw implementation. I'm closing it for now. If @glupiawymowka confirms that this issue still exist I'll reopen.

**Comment by glupiawymowka** [comment]
Hey, I'm re-opening this issue with more data from Marcin. Actually this time I was able to reproduce it **with the following steps**: 

1. logged in with metamask, address
0x8a194c13308326173423119F8dCb785CE14C732B
2. logout
3. **register** with lightwallet
4. vault created

`wallet: "{"encSeed":{"encStr":"dP48HjAEHW7CeaQyH9Q3POyYTWG5atmYmo3cNlYS+v7ErpEj1PDX+OYZnCAyPD/PqSOeSR7yu9mnpJDCx3oeYDsvbWjSGK0TpBkgR5c0H6YXdgqr9joMdUxbxPAkOvwiJ+Zc7tbEf1Yka9k1LgzNwmQXO6ft9gelxnUzd1gcyKPE6XZrRz+pxW00p/VMdHFNMch/yqYugr0T/OHW9TTMe2rS/nN8n7FcqrE9tDBv2gDk4UJfislnel8NwNaPf8ZipmofSQT8P7P99EAMWA2ozZZx5qiiybFIaSvnXxxiax9Xy60xRKq/1YlstPPxDUhK17sYUNjpUNw1sUHyIDgGWw==","nonce":"8L2DwhgZuRYfWvgoTvyBBHS/53J0QdI7"},"encHdRootPriv":{"encStr":"JwqDKG6lop215v9xUGttMTadZAMudkm+Bcu35AwvO9B1ZAucYXH1l4Ni4Gt1+f0fSUwhnWkKmg/kkEBouF8rfmvdoqQCBV+keRkBw+I9xujaYCRG0spdQLXdXwsxKYF02DRBnMckRLOIzwZdl1CdNRYcefOipyTFacAiLsXXdg==","nonce":"I0AWhdJSyyYwG5fQ/XMZZ5C4CK3u23WJ"},"addresses":["bc3f3ce1e6e1f77e3d1a40690b3af92ab576ec57"],"encPrivKeys":{"bc3f3ce1e6e1f77e3d1a40690b3af92ab576ec57":{"key":"aNZvaK8eBa6Wpok/J6A95xzXJFu9Oc1GCJavVXyP0mLfTTiQ/BG3mjd52SnpcKnn","nonce":"7qXJZetgpfxSjH4J2su/SO7z64Pwhpup"}},"hdPathString":"m/44'/60'/0'","hdIndex":1,"version":3}"`

address: bc3f3ce1e6e1f77e3d1a40690b3af92ab576ec57

5. challenge sent to backend

`{"address":"0x8a194c13308326173423119F8dCb785CE14C732B","salt":"ddfa6b11c7054e4de0eb50fd55f888cc44b8edba8eadc32a2fd6ddce0be31205","signer_type":"eth_sign","permissions":["sign-tos"]}`

so challenge is against old address that should be logged out!! but uses eth_sign so this is lightwallet
backend returns:

`7b2261646472657373223a2022307838613139346331333330383332363137333432333131394638644362373835434531344337333242222c202273616c74223a202264646661366231316337303534653464653065623530666435356638383863633434623865646261386561646333326132666436646463653062653331323035222c20227065726d697373696f6e73223a205b227369676e2d746f73225d2c202274696d657374616d70223a20313536353034393139312c20227369676e65725f74797065223a20226574685f7369676e222c20226d6163223a2022663235373339363939306534383365653734633537373338356139323731323363386364306639376366376633376363343534373939356364626663326162666665636638646231613739333636633839303665366163326466336235616566227d
{"address": "0x8a194c13308326173423119F8dCb785CE14C732B", "salt": "ddfa6b11c7054e4de0eb50fd55f888cc44b8edba8eadc32a2fd6ddce0be31205", "permissions": ["sign-tos"], "timestamp": 1565049191, "signer_type": "eth_sign", "mac": "f257396990e483ee74c577385a927123c8cd0f97cf7f37cc4547995cdbfc2abffecf8db1a79366c8906e6ac2df3b5aef"}`

6. signature is computed by lightwallet (probably) surely not Metamask
sent:

`{"challenge":"7b2261646472657373223a2022307838613139346331333330383332363137333432333131394638644362373835434531344337333242222c202273616c74223a202264646661366231316337303534653464653065623530666435356638383863633434623865646261386561646333326132666436646463653062653331323035222c20227065726d697373696f6e73223a205b227369676e2d746f73225d2c202274696d657374616d70223a20313536353034393139312c20227369676e65725f74797065223a20226574685f7369676e222c20226d6163223a2022663235373339363939306534383365653734633537373338356139323731323363386364306639376366376633376363343534373939356364626663326162666665636638646231613739333636633839303665366163326466336235616566227d","response":"0xf0f1a1b15e4d13d7790796130e5b28d7730410b3a3feb9146351a92c6aa0d25373572603bc73686e6db1d566e866f1d61f916a3327c36feb1d510cfb2111cf971c","signer_type":"eth_sign"}`

and you get 403 because different address signed it!


1. somehow we didn't erase previous address and we used it.
when I was logging in light wallet this is still present
{"address":"0x8a194c13308326173423119f8dcb785ce14c732b","walletType":"BROWSER","walletSubType":"METAMASK","userType":"investor"}
2. we are not checking if address in backend challenge corresponf to the wallet. we should refuse signing and log to sentry
I had to refresh the page to create lightwallet
