### ISSUE TITLE
[ETO COUNTDOWN] - fix behavior of the (pre)sale countdown

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3487]
**Description**
If the users are observing the presale (ald probably also public sale soon) countdown close to 00:00:00, they can notice two strange things: 

1. The counter is ~45 sec late regarding the computer clocks of everyone who tested. This screen was taken just after 15:00 (when the presale should start)

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b9f928d3-a2d0-4344-ac2c-615e6cb26be9)

2. There is an unknown state between the counter switching from 00:00:00 to "you can invest now". 
It shows the quote for a brief moment in between. 

Both issues you can watch recorded here:  https://neufund.slack.com/files/UFB18B665/FN6GVEB51/countdown_to_presale_ends-small.mov

**Environment**
stage (all?) 

**Steps To Reproduce**
The only way to properly see it now is to wait for the public sale or next ETO 

**Expected behavior**
- [ ] countdown is well integrated with the global clock, so the sale starts exactly at the time set
- [ ] there is no visible "unknown aka quote" state. It can flash at 00:00:00 until the investment state is available 

**Comments, context, logs**

**Screenshots**

**Comment by rudolfix** [comment]
technical notes
1. a ~40 second lag is observed on all browsers/OSes etc. and lag is same. IMO there's some debug constant build in then code somewhere! 
2. there's elaborate procedure for what happens when countdown reaches 0. maybe it;'s too complicated. what we should do is to
- start flashing countdown at 0 and below it put something like "waiting for the next block for [pre]sale to open"
- poll more frequently for contract state that will make whole thing reload

right now we have several fallbacks which does not work in the end - probably due this lag!

**Comment by rudolfix** [comment]
should be done together with #3502

**Comment by glupiawymowka** [comment]
tested on stage
