### ISSUE TITLE
Changing copy for users who have been successfully KYC'd by IDnow

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3604]
Right now a user that has been successfully verified using IDnow still needs to submit Proof of address, that is why wed like to change the copy here:
![idnow](https://user-images.githubusercontent.com/48217191/66569725-76954480-eb6c-11e9-9170-09f4b39a0924.png)

So only for those users, who have been successfully verified with ID now we should make these copy changes.
**Current copy**

 "Your identity is verified on the Ethereum blockchain. You may now invest in opportunities, sign legal agreements, claim dividends and other proceeds and vote on shareholder resolutions."

**New copy**

"Your identity is verified on the Ethereum blockchain. You may now invest in opportunities, sign legal agreements, claim dividends and other proceeds and vote on shareholder resolutions.
Additionally, we kindly ask you to submit a Proof of address - a recent utility bill or bank statement (from within the last 3 months). This document must include your full name, residential address, and date of issue. “

They should also have an option available (the upload button) to submit the additional documents.

**Comment by Louisswryan** [comment]
Design for KYC Cards is below.

**Provide more details before handover

https://share.goabstract.com/329d56e4-6568-4d39-9cec-652a0a102081?collectionLayerId=40d4b3d4-97ec-4f67-b488-f0a314c762bf&mode=design

**Comment by pstroinski** [comment]
Can you please look at this and specify for really needs to be done here? @andywalton

**Comment by andywalton** [comment]
@Louisswryan -> please will you review this ticket. I see the links in Zeplin no longer work as that project was archived. If you could what needs to be done here and update the ticket please (unarchive the Zeplin project etc.)

**Comment by Louisswryan** [comment]
Hello,

The current issue with this instance, is that the issuer may opt to change the date of their eto and, if there is already a transaction pending, the 'ETO DATE' card will remain in a pending state for a very long time with no information to confirm that there is a process underway. 

This instance is seen attached below.

![Screenshot 2020-03-04 at 11.47.25.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/fba15cab-a2db-4e75-b2ad-fd53a7190faf)

The solution is to include a generic pending message into this card state: 
"There is a pending process. Please wait…"

Seen here: https://zpl.io/bWJ6rze

The reason for this to be generic, is so that it is reusable across many different instances of the same component although we will handle further instances in separate tickets.

Please ask with questions,

Thanks

**Comment by Louisswryan** [comment]
This ticket has been resolved by changes to our onboarding. 

We now ask for proof of address as part of the address step, just before KYC.

The user cannot move past this point without uploading something so this situation with a complete KYC but overdue proof of address will simply not arise.

Closing this ticket.
