### ISSUE TITLE
Migrate input label to new design

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3748]
**Background**
The existing label needs to be replaced to match new NDS. Besides UI changes (roboto font, uppercase) we are also changing the way we mark a field as required. Previously all required fields consisted of the red star `*` at the end of a label. Now we are moving away from `*` to use `(optional)` wording in case field is not required.

**Designs**
We don't have any style guide yet for new inputs but as a reference, you can use designs from new KYC forms: zpl.io/bzjPdP7

**Acceptance criteria**
- [x] All field labels use the new design
- [x] All optional fields are marked with `(optional)` at the end of a label

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
- [ ] Lato used in email label 
![image](https://user-images.githubusercontent.com/18315589/69158482-cd385b80-0ae6-11ea-8b96-6fdf95ed2df1.png)


- [ ] this should not be optional, backoffice requests this data if empty  (it's not a part of this PR, but if it's an easy fix please do it, I'll open a new ticket otherwise)
Please remove both (optional) and (if applicable) and treat as obligatory
![image](https://user-images.githubusercontent.com/18315589/69236047-03331980-0b93-11ea-8d25-769224ac348f.png)
![image](https://user-images.githubusercontent.com/18315589/69243743-f79c1e80-0ba3-11ea-8387-f658b4916179.png)


- [ ] everything but Pitch Deck link is optional here, but not marked as such 
![image](https://user-images.githubusercontent.com/18315589/69242748-d9352380-0ba1-11ea-978b-f7df39a4c544.png)

**Comment by glupiawymowka** [comment]
tested on stage
