### ISSUE TITLE
Button fixes to match button states to the latest as per NDS

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3821]
Hey, we've made a few small tweaks to the button designs.

This tickets task is to match the hover button states for the:
1. `.btn-primary` - Primary button 
2. `.btn-secondary` - Secondary button (formerly called Outline)
3. `.btn-link` - Link button (formerly called Ghost)

The hover state and active states are the same and they use our darker brand yellow with our base gray for button labels and icons:
```
$yellow-darker-1
#C6D30D
```

The text and icons are the same as the button label:
```
$base-gray
#142431
```

Also note, there are four height size modifiers for buttons:
1. Default = 40px height 
2. Extra small = 24px height 
3. Small = 32px height 
4. Large = 48px height

We also have a circular button - this is already correctly developed and it's only used in our Documents section. It however can be used at any of the above sizes and it's hover state and disabled states would be the same as the other buttons listed above. 

**Designs:**
View the below in Zeplin: https://zpl.io/agBnxDA

The buttons should look like the below at each state changes:

![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/973e15a5-32c0-4de4-bda5-2b43a979c684)

![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/8e16cdaa-db11-4c6a-8925-913d5b77ef29)

![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/f5026729-f2ea-436e-aee4-e6acc40f59d9)

---

![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/9c9f7201-e333-4503-ba75-cb6534134305)

Icons, a button can either have a leading icon or a trailing icon, or only an icon. The space between the icon and button label should be `8px` and the icon colour should always match the label colour. So when it's disabled, the button label changes to a different gray, so should the icon which should match it.

---

The main fix for this ticket please is to match...
- [ ] the hover states - as described above, currently we have an incorrect button hover states on the platform. For example, the primary button has a drop shadow which should rather be removed.

Once that is done this ticket can be pushed for testing.

The rest is a bonus, if you do anything else, please just mention it in the PR.

Thanks,
Andy

**Comment by glupiawymowka** [comment]
moving back to in progress due to some possible build issues

**Comment by glupiawymowka** [comment]
This ticket was merged without the full test and it came out that it's only partly done. 
There was a request to not only edit the styling, but also the naming in the button class. The aim of the change was to avoid similar mishmash in future changes. 

I can see that some of the stylings were adjusted as per design, but there are some issues: 

- [ ] The `Log in` button has correct styling, but incorrect class name (it was supposed to be `.btn-secondary`, it is `.btn-outline`)
![image](https://user-images.githubusercontent.com/18315589/78666960-6e7a4f80-78d8-11ea-9c0f-71f3d89b549c.png)

- [ ] There is a class called `button--secondary` but it's also wrong because:
- it looks disabled while it's not
- `button--primary` is the class to use for a single-button modals
![image](https://user-images.githubusercontent.com/18315589/78668467-08db9280-78db-11ea-9bd4-44487f1cb8d6.png)


- [ ] Link buttons were supposed to be classified as `.btn-link` instead of current `button--ghost`
![image](https://user-images.githubusercontent.com/18315589/78668969-d9795580-78db-11ea-822c-9386b6e4868c.png)
