### ISSUE TITLE
neufund.org check the routings

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#395]
Pls. check the old and new rootings and make sure they work. 

we have lot's of old links postings on different sites.
https://neufund.org/careers/ in this format. dosn't work :)

Pls. compare and update.
 Some old links like /team if they don't exist need to leed to about-us etc. 

Pls. assign this to Andrzej  is he is able to cope with this.

**Comment by TomaszWaszczyk** [comment]
Just a kindly note that on https://neufund.org/careers/ I have:

404 Not Found
nginx/1.12.1

**Comment by banciur** [comment]
@SergejSoft there is list (bottom of speardsheet from 23rd record) with redirects that will handle old links. https://docs.google.com/spreadsheets/d/1uU77DA-Zqiq2H_Mtqg13dzeme5PKcIRxEDkGZoKLt88/edit?usp=sharing

`/team` is not there as since long time it wasn't present on our website. Team was part of /community page.

Problem with url's with trailing slash I confirm and already fixed now we are waiting for deploy.
