### ISSUE TITLE
[ETO widget] - Target Investment amount got hidden

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3955]
**Description**

While ETO is doing marketing publishing, the investment details don't need to be provided yet, so we hide it under TBA's. 
This is correct, but all the data should be available as soon as the issuer's term sheet gets accepted. 
Currently, we show everything besides the target investment amount. 

This is important to be fixed soon, as the next ETO is reaching the "accepted TS" case soon 

**Env** 
All 

**Steps to reproduce**
on .io, just open any ETO that has TS accepted, but is not in the presale yet, like https://platform.neufund.io/eto/view/LI/828dddce-adc7-417f-a9a3-51e879b9cd82

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4def790e-f58e-469b-9fe1-8243e2386ebe)

**Acceptance criteria**

- [ ] all the investment terms are hidden as TBA before TS gets accepted
- [ ] all the investment terms values are shown after TS gets accepted

**Comment by Moejoe90** [comment]
I'm not sure if this is fully a frontend issue.

The issue comes from the fact that we take this data from the smart contract and the smart contract at this stage has the inital data `0` based on the response from the `node` 

At the current state for the ETO mentioned in the ticket the data is not initialized. 

What I'm not sure of is if this is a `fixture` issue or simply this is how it should work

**Comment by glupiawymowka** [comment]
tested on stage for states before and after publishing the investment terms
